import { StyleSheet } from 'react-native';
import { colors, fontFamily, radius, spacing, typography } from '../theme';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.containerMargin,
    paddingVertical: spacing.gutter,
    backgroundColor: colors.surface,
  },
  closeBtn: {
    width: 40, height: 40, borderRadius: 9999,
    alignItems: 'center', justifyContent: 'center',
  },
  closeBtnPressed: { backgroundColor: colors.surfaceContainerHigh },
  title: { ...typography.headlineSm, fontFamily: fontFamily.bold, color: colors.onSurface },
  content: {
    paddingHorizontal: spacing.containerMargin,
    paddingVertical: spacing.stackLg,
    gap: spacing.stackLg,
  },
  typeToggle: {
    flexDirection: 'row',
    backgroundColor: colors.surfaceContainerLow,
    padding: 4,
    borderRadius: radius.xl,
  },
  typeBtn: {
    flex: 1,
    paddingVertical: spacing.md,
    alignItems: 'center',
    borderRadius: radius.lg,
  },
  typeBtnActive: { backgroundColor: colors.secondary },
  typeText: { ...typography.labelLg, fontFamily: fontFamily.medium, color: colors.onSurfaceVariant },
  typeTextActive: { color: colors.onSecondary, fontFamily: fontFamily.bold },

  amountBlock: { alignItems: 'center', gap: spacing.sm },
  amountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  currencyChip: {
    backgroundColor: colors.surfaceContainerLow,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  currencyText: {
    ...typography.headlineMd,
    fontFamily: fontFamily.semibold,
    color: colors.secondary,
  },
  amountInput: {
    ...typography.numeralXl,
    fontFamily: fontFamily.bold,
    color: colors.onSurface,
    width: 200,
  },

  field: { gap: spacing.sm },
  label: {
    ...typography.labelLg,
    fontFamily: fontFamily.medium,
    color: colors.onSurfaceVariant,
    paddingHorizontal: spacing.xs,
  },
  selectBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colors.surfaceContainerLow,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    borderRadius: radius['2xl'],
    paddingHorizontal: spacing.gutter,
    paddingVertical: spacing.md,
  },
  selectBtnPressed: { backgroundColor: colors.surfaceContainer },
  selectText: {
    ...typography.bodyMd,
    fontFamily: fontFamily.regular,
    color: colors.onSurface,
    flex: 1,
    textAlign: 'right',
  },
  noteInput: {
    backgroundColor: colors.surfaceContainerLow,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    borderRadius: radius['2xl'],
    paddingHorizontal: spacing.gutter,
    paddingVertical: spacing.md,
    color: colors.onSurface,
    fontFamily: fontFamily.regular,
    fontSize: 16,
    minHeight: 100,
    textAlignVertical: 'top',
  },
  error: {
    ...typography.labelLg,
    color: colors.error,
    textAlign: 'right',
  },
  footer: {
    paddingHorizontal: spacing.containerMargin,
    paddingTop: spacing.gutter,
    borderTopWidth: 1,
    borderTopColor: colors.white05,
    backgroundColor: colors.background,
  },
  submitBtn: {
    backgroundColor: colors.secondary,
    borderRadius: radius.full,
    paddingVertical: spacing.md,
    alignItems: 'center',
  },
  submitText: {
    ...typography.bodyMd,
    fontFamily: fontFamily.bold,
    color: colors.onSecondary,
  },
});
